language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

script:
  - yarn lint
  - yarn coveralls

after_script:
  - "cat ./coverage/lcov.info | coveralls"
  - "bash <(curl -s https://codecov.io/bash)"

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: joaaomanooel-books-api
  on:
    branch: master
    all_branches: false
    repo: joaaomanooel/books-api
