language: node_js
node_js:
 - "10.10.0"
script:
  - NODE_ENV=test npm run test:converage
cache:
  directories:
    "node_modules"
    ".travis.yml"
after_script: "cat ./coverage/lcov.info | coveralls"
